
# 启动端口号
server:
  port: 9488
  tomcat:
    uri-encoding: UTF-8
  # 设置最大http传输header大小
  max-http-header-size: 80KB

# 配置数据源信息

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://39.106.215.59:3306/foodie-shop-dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    url: jdbc:mysql://localhost/foodie_shop?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.synear.ThreadPool.pojo


redis:
  host: 192.168.137.100
  port: 6379
  password: 123456
  timeout: 30000
  # 连接池最大连接数（使用负值表示没有限制）
  maxTotal: 30
  # 最大空闲数
  maxIdle: 10
  # 连接池最大阻塞等待时间（使用负值表示没有限制）/ 获取连接时的最大等待毫秒数,小于零:阻塞不确定的时间,默认-1
  maxWaitMillis: 1500
  # 做空闲连接检测时，每次的采样数 / 每次释放连接的最大数目
  numTestsPerEvictionRun: 1024
  # 空闲连接的检测周期，单位为毫秒 / 释放连接的扫描间隔（毫秒）
  timeBetweenEvictionRunsMillis: 30000
  # 连接的最小空闲时间，达到此值后空闲连接将被移除
  minEvictableIdleTimeMillis: 1800000
  # 连接空闲多久后释放, 当空闲时间>该值&&空闲连接>最大空闲连接数=>直接释放
  softMinEvictableIdleTimeMillis: 10000
  # 向连接池借用连接时是否做连接有效性检测(Ping)无效连接将会被删除 / 在获取连接的时候检查有效性, 默认false
  testOnBorrow: true
  # 向连接池借用连接时是否做空闲检测，空闲超时的将会被移除 / 在空闲时检查有效性, 默认false
  testWhileIdle: true
  # 当连接池资源耗尽时，调用者是否需要等待。和maxWaitMillis对应，当它为true时，maxWaitMillis生效 / 连接耗尽时是否阻塞, false报异常,true阻塞直到超时, 默认true
  blockWhenExhausted: false
